<?php

namespace App\Http\Controllers;

use App\Traits\BaseResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\VehicleBrand;
use App\Models\VehicleModel;

class TestController extends Controller
{
    use BaseResponse;

    public function index(Request $request)
    {
        $cars =[
    'Abarth'=>[
        '124 Spider',
        '595',
    ],
    'Acura'=>[
        'ILX',
        'MDX',
        'TL',
    ],
    'Alfa Romeo'=>[
        '156',
        'Giulia',
        'Stelvio',
    ],

    'AMC'=>[
        'Matador',
    ],
    'Aprilia'=>[
        'RS 125',
        'RS 660',
        'Tuona 660',
    ],
    'Ashok Leyland'=>[
        'Eagle 816',
    ],
    'Aston Martin'=>[
        'Rapide',
        'V8 Vantage',
    ],
    'ATV'=>[
        '150',
    ],
    'Audi'=>[
        '100',
        'A1',
        'A3',
        'A4',
        'A4 allroad',
        'A5'=>[
            'A5',
            'A5 Sportback'
        ],
        'A6',
        'A6 allroad',
        'A7'=>[
            'A7',
            'A7 Sportback'
        ],
        'A8',
        'Q2',
        'Q2 e-tron',
        'Q3',
        'Q5',
        'Q5 Sportback',
        'Q5 e-tron',
        'Q7',
        'Q8',
        'Q8 Sportback  e-tron',
        'Q8  e-tron',
        'R8',
        'RS4',
        'RS7',
        'S5',
        'S8',
        'TT',
        'e-tron',
        'e-tron S',
        'e-tron Sportback',
    ],
    'Avatr'=>[
        '11',
    ],
    'Avia'=>[
        '31',
    ],

    'Baic'=>[
        'A1',
        'M60',
        'Senova D50',
        'Senova D70',
        'X3',
        'X55',
        'X55 ||',
        'X77',
    ],

    'Bajaj'=>[
        'Avenger 220',
        'Dominar 250',
        'Dominar 400',
        'Pulsar NS 160',
        'Pulsar NS 200',
        'Pulsar RS 200',
    ],

    'Bentley'=>[
        'Bentayqa',
        'Continental',
        'Continental Flying Spur',
        'Continental GT',
        'Flying Spur',
        'Mulsanne',
    ],

    'Bestune'=>[
        'B70S',
        'NAT',
        'T55',
        'T77',
        'T99'
    ],

    'BMC'=>[
        'Pro 827',
        'Pro 837'
    ],

    'BMW'=>[
        '1-serias'=>[
            '116',
            '118',
            '120',
        ],
        '2-serias'=>[
            '218',
            '120',
        ],
        '3-serias'=>[
            '316',
            '318',
            '320',
            '320e',
            '323',
            '325',
            '328',
            '330',
            '330 GT',
            '330e',
            '335',
        ],
        '4-serias'=>[
           '420',
           '428',
           '430',
           '435',
        ],
        '5-serias'=>[
            '518',
            '520',
            '520e',
            '523',
            '525',
            '528',
            '530',
            '530e',
            '535',
            '540',
            '545',
            '550',
        ],
        '6-serias'=>[
            '630',
            '640',
            '645',
            '650',
        ],
        '7-serias'=>[
            '728',
            '730',
            '735',
            '740',
            '740Le',
            '745',
            '745Le',
            '750',
            '750e xDrive',
            '760',
        ],
        '8-serias'=>[
            '840',
        ],
        'BMW Moto'=>[
            'K 1600 GT',
            'S 1000 RR',
        ],
        'M-serias'=>[
            'M3',
            'M340',
            'M5',
            'M6',
            'M760 xDrive',
            'M8',
            'X5 M',
            'X6 M',
            'XM',
        ],
        'X-serias'=>[
            'X1',
            'X2',
            'X3',
            'X4',
            'X5',
            'X6',
            'X7',
        ],
        'i-serias'=>[
            'i3',
            'i4',
            'i5',
            'i7',
            'i7 M70',
            'i8',
            'iX',
            'iX 1',
        ]
    ],

    'BMW Alpina'=>[
        'B10',
        'B5',
        'B7'
    ],
    'Brilliance'=>[
        'M2 (BS4)'
    ],
    'Buick'=>[
        'Enclave',
        'Encore',
        'LaCrosse',
    ],
    'BYD'=>[
        'Destroyer 05',
        'F3',
        'Frigate 07',
        'Han',
        'Qin Plus',
        'Seal',
        'Song',
        'Song Plus',
        'Tang',
        'Yuan Plus',
        'e2',
    ],
    'C.Moto'=>[
        'CM250R-HY',
        'CM400R-18',
        'CM400R-F8',
        'CM400R-HY',
        'CM400R-HY',
        'CMR-F7',
        'CMR-RZ',
        'CMR-SY',
        'CMR-YZ',
    ],
    'Cadillac'=>[
        'ATC',
        'CT4',
        'CT5',
        'CT6',
        'CTS',
        'ELR',
        'Escalade',
        'SRX',
        'XTS',
    ],
    'Can-Am'=>[
        'Spyder F3',
        'Spyder RT'
    ],
    'CFMOTO'=>[
        'ATV'=>[
            'CFORCE 1000 OVERLAND',
            'CFORCE 520L',
            'CFORCE 600 TOURING',
            'CFORCE-ATV-625',
        ],
        'Moto'=>[
            '450 SR',
            '450 SR-S',
            '650 MT',
            '700 CL-X Heritage',
            '700 CL-X Sport',
            '800 MT Explore',
            '800 MT Touring',
        ],
        'Sport SIDE X SIDES'=>[
            'ZFORCE 1000 Sport R'
        ]
    ],

    'Changan'=>[
        'Alsvin',
        'Alsvin V3',
        'Alsvin V5',
        'Alsvin V7',
        'Benni',
        'Benni E-Star',
        'CS 15',
        'CS 35',
        'CS 35 Plus',
        'CS 55 Plus',
        'CS 75',
        'CS 75 Plus',
        'CS 85',
        'CS 95',
        'CX 20',
        'Deepal'=>[
            'Deepal S7'
        ],
        'Eado',
        'Eado DT',
        'Eado Plus',
        'F70 (Hunter)',
        'Honor',
        'Oshan'=>[
            'Oshan Z6'
        ],
        'Oshan A600',
        'Qiyuan'=>[
            'Qiyuan A05',
            'Qiyuan A06',
            'Qiyuan A07'
        ],
        'Raeton',
        'Star',
        'Uni-K',
        'Uni-K-iDD',
        'Uni-T',
        'Uni-V',
        'Uni-V',
    ],
    'Chery'=>[
        'Amulet(A15)',
        'Arrizo 5',
        'Arrizo 7',
        'Eastar(B11)',
        'Fora(A21)',
        'Fulwin 2',
        'Kimo (A1)',
        'Sweet (QQ)',
        'Tiggo (T11)',
        'Tiggo 2',
        'Tiggo 2 Pro',
        'Tiggo 3',
        'Tiggo 7 Pro',
        'Tiggo 7 Pro e+',
        'Tiggo 8 Pro',
        'Tiggo 8 Pro Max',
        'Tiggo 8 Pro e+',
    ],
    'Chevrolet'=>[
        'Avalanche',
        'Aveo',
        'Blazer',
        'Bolt',
        'Camaro',
        'Captiva',
        'Cobalt',
        'Colorado',
        'Corvette',
        'Cruze',
        'Damas',
        'Epica',
        'Equinox',
        'Express',
        'Labo',
        'Lacetti',
        'Lanos',
        'Malibu',
        'Menlo',
        'Monzo',
        'Nexia',
        'Niva',
        'Onix',
        'Orlando',
        'Rezzo',
        'Sonic',
        'Spark',
        'Suburban',
        'Tahoe',
        'Tracker',
        'TrailBlazer',
        'Trax',
        'Volt',
    ],
    'Chrysler'=>[
        '200',
        '300',
        '300C',
        'Concorde',
        'PT Cruiser',
        'Pacifica',
        'Voyager',
    ],
    'Citroen'=>[
        'Berlingo',
        'C-Elysee',
        'C3',
        'C3 Picasso',
        'C4',
        'C4 Picasso',
        'C5',
        'C5 Aircross',
        'DS3',
        'DS4',
        'DS5',
        'Jumpy',
    ],
    'Dacia'=>[
        'Dokker',
        'Lodgy',
        'Logan',
        'Sandero',
    ],
    'Daewoo'=>[
        'Ace (Super Salon)',
        'BH117',
        'BS090',
        'Damas',
        'Espero',
        'Gentra',
        'Lacetti',
        'Lanos',
        'Leganza',
        'Lublin',
        'Matiz',
        'Nexia',
        'Nubira',
        'Prince',
        'Racer',
        'Tico',
    ],
    'DAF'=>[
        '105 XF',
        '75 CF',
        '85 CF',
        '95',
        '95 XF',
        'LF 45.180',
        'XF 460 FT',
        'XF 460 FT',
        'XF 480',
    ],
    'Daihatsu'=>[
        'Terios'
    ],
    'Dayun'=>[
        'DY150-12'
    ],
    'Denza'=>[
        'D9'
    ],
    'DFSK'=>[
        'C-32 S',
        'C-35',
        'C-37',
        'D51',
        'E5',
        'Glory 330',
        'Glory 330 S',
        'Glory 330 S Cargo',
    ],
    'Dnepr'=>[
        '11',
        'K-750',
    ],
    'Dodge'=>[
        'Challenger',
        'Charger',
        'Dart',
        'Durango',
        'Journey',
        'Nitro',
        'Ram',
        'Stratus',
    ],
    'DongFeng'=>[
        'Aeolus'=>[
            'Aeolus H30',
            'Aeolus Huge',
            'Aeolus S30',
            'Aeolus Shine Max',
        ],
        'DFL3310A13',
        'EQ 220'
    ],
    'Ducati'=>[
        '1199 Panigale S',
        '848 EVO',
    ],
    'FAW'=>[
        'Besturn X80',
        'J6P dumper 6x4',
        'J6P dumper 8x4',
        'Micro Bus'=>[
            'CA6350'
        ],
        'Oley',
        'SUV'=>[
            'CA1021P6LU2E'
        ],
        'Tiger VH',
        'Tiger VH-L',
        'Tiger VN',
        'Tiger VR',
    ],
    'Ferrari'=>[
        'California'
    ],
    'Fiat'=>[
        '500',
        '500C',
        '500L',
        'Albea',
        'Bravo',
        'Cinquecento',
        'Doblo',
        'Ducato',
        'Fiorino',
        'Linea',
        'Panda',
        'Punto',
        'Qubo',
        'Tempra',
        'Tipo',
        'Ulysse',
    ],
    'Foday'=>[
        'NHQ'
    ],
    'FORD'=>[
        'Bronco',
        'Bronco Sport',
        'C-MAX',
        'Cargo',
        'Cougar',
        'Courier',
        'Ecosport',
        'Edge',
        'Escape',
        'Escort',
        'Explorer',
        'F-150',
        'F-450',
        'Fiesta',
        'Focus',
        'Fusion',
        'Galaxy',
        'Kuga',
        'Maverick',
        'Mercury',
        'Mondeo',
        'Mustang',
        'Mustang Mach-E',
        'Puma',
        'Ranger',
        'Sierra',
        'Tourneo Connect',
        'Tourneo Custom',
        'Transit',
    ],
    'Foton'=>[
        'Aumark TX',
        'BJ1027',
        'Forland',
        'Ollin',
    ],
    'GAC'=>[
        'Aion'=>[
            'Aion S',
            'Aion S Max',
            'Aion Y Plus',
        ],
        'Trumpchi'=>[
            'Trumpchi GA5',
            'Trumpchi GS4',
            'Trumpchi GS5',
        ]
    ],
    'GAZ'=>[
        '12 ЗИМ',
        '221717',
        '231073',
        '24',
        '24-02',
        '24-10',
        '2705',
        '2705-757',
        '2705-764',
        '2705-777',
        '27057',
        '27527-745',
        '2757',
        '27903',
        '3102',
        '31029',
        '3110',
        '31105',
        '322173',
        '3302-288',
        '3302-744',
        '330200',
        '330200',
        '33023-744',
        '330232-744',
        '33027',
        '33027-745',
        '3307',
        '3308',
        '51',
        '52',
        '53',
        '66',
        '99',
        'A21R22-03',
        'Biznes 330273',
        'C41R13',
        'C41R92',
        'C45R02',
        'Gazon C41R33',
        'M-20 Pobeda',
        'M-21',
        'NEXT A68R52 CITY LINE',
        'Next',
        'Next A21R22-30',
        'Next A22R32',
        'Next A23R22',
        'Next A31R22',
        'Next A32R32-40',
        'Next A65R32-40',
        'Next A65R52',
        'Next C41RB3',
        'Next A31R32',
        'SAZ-3507',
        'Sadko C42A43',
        'Sobol',
        'Volgo Siber',
    ],
    'Geely'=>[
        'Atlas Pro',
        'CK',
        'Coolray',
        'Emgrand',
        'Emgrand 7 (RV)',
        'Emgrand EC7',
        'Emgrand TX4',
        'ICON',
        'MK',
        'Monjaro',
        'Okavango',
        'Radar RD6',
        'TX4',
        'Tugella'=>[
            'Tugella',
            'Tugella S',
            'Tugella S',
        ]
    ],
    'GWM'=>[
        'Florid',
        'Hover',
        'Hover H3',
        'Hover H5',
        'Hover M2',
        'Hover M5',
        'Ora'=>[
            'Ora'
        ],
        'Pegasus',
        'Poer',
        'Tank'=>[
            'Tank 300',
            'Tank 500'
        ],
        'Voleex C30',
        'Voleex C50',
        'Wingle',
    ],
    'GMC'=>[
        'Acadia',
        'Savana',
        'Terrain',
        'Yukon',
    ],
    'Grandmoto'=>[
        'Nova',
        'Volcano',
    ],
    'Haval'=>[
        'Dargo',
        'F7x',
        'H2',
        'H6',
        'H6 GT',
        'H8',
        'H9',
        'Jolion',
        'M6',
    ],
    'HiPhi'=>[
        'X',
        'Z',
    ],
    'Hondo'=>[
        'Accord',
        'CR-V',
        'City',
        'Civic',
        'Clarity',
        'Fit',
        'HR-V',
        'Hondo Moto'=>[
            'CB300R',
            'CB650R',
            'CBR 250',
            'CBR 600',
            'Spacy',
        ],
        'Insight',
        'M-NV',
        'Pilot',
        'Ridgeline',
        'e:NP1',
        'e:NS1',
    ],
    'Harley-Davidson'=>[
        'FLHR Road King',
        'FLHR Street Glide',
        'FLSTC Heritage Softail Classic',
        'FLTRX Road Glide',
        'Road Glide ST',
        'Softail Deluxe',
        'Softail Fat Boy',
        'Sportster Custom 1200',
        'Sportster Roadster',
        'Sportster S',
        'Street Rod',
        'Touring Electra Glide',
        'Touring Street Glide',
        'XL883N Sportster Iron 883',
        'XR1200X',
    ],
    'Haojue'=>[
        'DR 160 S',
        'HJ125-11A',
        'HJ125T-18A',
        'HJ150-2C',
        'KA150',
        'TR150S',
        'TZ125',
        'TZ125'
    ],
    'Haima'=>[
        '8S'
    ],
    'Hongqi'=>[
        'E-HS9',
        'H5',
        'HS5',
        'HS7',
    ],
    'HOWO'=>[
        '3241V',
        '371',
        'A7',
        'Shacman F2000',
        'Sinotruk'
    ],
    'Hummer'=>[
        'H2',
        'H3',
    ],
    'Hyundai'=>[
        'Accent',
        'Atos',
        'Azera',
        'Chorus',
        'County',
        'Coupe',
        'Create',
        'Creta',
        'Elantra',
        'Equus',
        'Excel',
        'Galloper',
        'Genesis',
        'Genesis Coupe',
        'Getz',
        'Grand Santa Fe',
        'Grandeur',
        'H 100',
        'H-1',
        'HD-120',
        'HD-35',
        'HD-45',
        'HD-65',
        'HD-72',
        'HD-78',
        'IONIQ',
        'IONIQ 5',
        'KONA',
        'Matrix',
        'Mighty EX6',
        'Mighty EX8',
        'Mufasa',
        'Palisade',
        'Santa Cruz',
        'Solaris',
        'Sonata',
        'Staria',
        'Terracan',
        'Tucson',
        'Veloster',
        'Venue',
        'Venue',
        'Veracruz',
        'Verna',
        'XG',
        'i10',
        'i20',
        'i30',
        'i40',
        'ix35',
        'ix55',
    ],
    'IJ'=>[
        '2126 Oda',
        '2717',
        '27175',
        'IJ Moto'=>[
            'Planeta 5',
            'Upiter 4'
        ],
    ],
    'IM'=>[
        'L7',
        'LS6',
        'LS7',
    ],
    'Indian Motorcycle'=>[
        'Challenger',
        'Pursuit',
    ],
    'Infiniti'=>[
        'EX-series'=>[
            'EX35'
        ],
        'FX-series'=>[
            'FX35',
            'FX37',
        ],
        'G-series'=>[
            'G20',
            'G25',
            'G35',
            'G37',
            'G37S',
        ],
        'JX-series'=>[
            'JX35'
        ],
        'Q-series'=>[
            'Q30',
            'Q45',
            'Q50',
            'Q50S',
            'Q70',
            'QX4',
            'QX4',
        ],
        'QX-series'=>[
            'QX30',
            'QX50',
            'QX55',
            'QX56',
            'QX60',
            'QX70',
            'QX70S',
            'QX80',
        ]
    ],
    'Iran Khodro'=>[
        'Runna',
        'Samand',
        'Soren',
    ],
    'Isuzu'=>[
        'Bogdan',
        'Citybus',
        'Ecobus',
        'FSR 90 L',
        'FVR 34 Q',
        'Forward',
        'MD 22 B',
        'NHR 55 E',
        'NKR 55 E',
        'NKR 55 L',
        'NMR 77 H',
        'NMR 85 H',
        'NPR',
        'NPR 400',
        'NPR 66 L',
        'NPR 71',
        'NPR 75 K',
        'NPR 75 L',
        'NPR75L-K',
        'NQR 71 PL',
        'NQR 75',
        'NQR90L-K',
        'Novo Lux',
        'Turkuaz',
    ],
    'Iveco'=>[
        '35S10',
        'Astra HD8',
        'Daily 30-8',
        'Daily 35C12H',
        'Daily 35C12VH',
        'EuroStar',
        'Eurocargo',
        'Otoyol',
        'Power Daily A50.13',
        'Stralis',
        'Trakker',
    ],
    'JAC'=>[
        'HFC 1040K',
        'HFC1061K5P',
        'HFC1083K',
        'HFC3072',
        'J5',
        'J7',
        'JS4',
        'JS8',
        'T6',
        'T8',
    ],
    'Jaguar'=>[
        'E-Pace',
        'F-Pace',
        'F-Pace R',
        'F-Type',
        'F-Type R',
        'F-Type S',
        'I-Pace',
        'X-Type',
        'XE',
        'XF',
        'XJ L',
        'XJ Sovereign',
        'XKR-S',
    ],
    'Jawa'=>[
        '350'
    ],
    'Jeep'=>[
        'Cherokee',
        'Commander',
        'Compass',
        'Gladiator',
        'Grand Cherokee',
        'Patriot',
        'Renegade',
        'Wrangler',
    ],
    'Jetour'=>[
        'Dashing',
        'T2',
        'X70',
        'X70 Plus',
        'X90 Plus',
        'X95',
        'X95',
    ],
    'Jiangmen'=>[
        'Nav 450',
        'Nav 500',
        'RG storm',
        'RGMT',
        'RGV8',
        'RY 125',
        'S5',
    ],
    'Jianshe'=>[
        'JS400 ATV'
    ],
    'JMC'=>[
        'N601'
    ],
    'KAIYI'=>[
        'X3 Pro'
    ],
    'KamAz'=>[
        '4308',
        '43101',
        '43118',
        '5320',
        '53202',
        '53212',
        '53213',
        '53229',
        '5410',
        '54112',
        '54115',
        '5511',
        '55111',
        '65115',
        '6520',
        '6520',
    ],
    'Kanuni'=>[
        'Mati 125',
        'Nev 50',
        'Trodon XS 50',
        'Visal 125',
    ],
    'Karry'=>[
        'Dolphin'
    ],
    'Kawasaki'=>[
        'ER6N',
        'Ninja 300',
        'Ninja 400',
        'Ninja 650',
        'VN 900 Vulcan',
        'Versys 650',
        'Z650'
    ],
    'KG Mobility'=>[
        'Musso',
        'Rexton',
        'Rexton Sports',
        'Tivoli',
        'Torres',
        'XLV',
    ],
    'Khazar'=>[
        'LX',
        'SD',
    ],
    'Kia'=>[
        'Avella',
        'Bongo',
        'Cadenza',
        'Carens',
        'Carnival',
        'Ceed',
        'Ceed SW',
        'Cerato',
        'Cerato Koup',
        'Clarus',
        'Credos',
        'EV5',
        'EV6',
        'EV9',
        'K2700',
        'K3',
        'K4',
        'K5',
        'K7',
        'K8',
        'Magentis',
        'Mohave',
        'Morning',
        'Niro',
        'Opirus',
        'Optima',
        'Pegas',
        'Picanto',
        'Pregio',
        'Pride',
        'ProCeed',
        'Quoris',
        'Ray',
        'Rio',
        'Rio X-Line',
        'Seltos',
        'Sephia',
        'Shuma',
        'Sorento',
        'Soul',
        'Sportage',
        'Stinger',
        'Stonic',
        'Venga',
    ],
    'King Long'=>[
        'XMQ612AYW'
    ],
    'Kinroad'=>[
        'XT50QT-8'
    ],
    'KrAz'=>[
        '65053'
    ],
    'KTM'=>[
        '390 Duke',
        '690 Duke',
    ],
    'Kuba'=>[
        'Ege 50',
        'X-boss',
    ],
    'LADA(VAZ)'=>[
        '2101',
        '21011',
        '21013',
        '2102',
        '2103',
        '2104',
        '21045',
        '2105',
        '2106',
        '2107',
        '2108',
        '2109',
        '21099',
        '2110',
        '2111',
        '2112',
        '2113',
        '2114',
        '2115',
        'Granta',
        'Granta Cross',
        'Kalina',
        'Largus'=>[
            'Largus',
            'Largus Cross',
        ],
        'Niva',
        'Niva Bronto',
        'Niva Travel',
        'Niva Oka',
        'Priora',
        'Vesta'=>[
            'Vesta',
            'Vesta Cross',
            'Vesta SW Cross',
        ],
        'XRAY'=>[
            'XRAY Cross',
        ],
    ],
    'Lamborghini'=>[
        'Urus'
    ],
    'Lancia'=>[
        'Lybra'
    ],
    'Land Rover'=>[
        'Defender',
        'Discovery',
        'Discovery Sport',
        'Freelander',
        'RR Evoque',
        'RR Sport',
        'RR Velar',
        'Range Rover',
    ],
    'Leapmotor'=>[
        'C11',
        'T03',
    ],
    'Lexus'=>[
        'CT-series'=>[
            'CT 200h'
        ],
        'ES-series'=>[
            'ES 200',
            'ES 250',
            'ES 300',
            'ES 300h',
            'ES 350',
        ],
        'GS-series'=>[
            'GS 200t',
            'GS 250',
            'GS 300',
            'GS 350',
            'GS 430',
            'GS 450h',
            'GS 450h',
        ],
        'GX-series'=>[
            'GX 460',
            'GX 470',
        ],
        'IS-series'=>[
            'IS 200',
            'IS 250',
            'IS 300',
        ],
        'LS-series'=>[
            'LS 350',
            'LS 460',
            'LS 500',
        ],
        'LX-series'=>[
            'LX 450',
            'LX 470',
            'LX 500d',
            'LX 570',
            'LX 600',
        ],
        'NX-series'=>[
            'NX 200',
            'NX 200t',
            'NX 250',
            'NX 300',
            'NX 300h',
            'NX 350',
            'NX 350h',
        ],
        'RC-series'=>[
            'RC 200t'
        ],
        'RX-series'=>[
            'RX 200t',
            'RX 300',
            'RX 330',
            'RX 350',
            'RX 350h',
            'RX 450h',
            'RX 500h',
        ],
        'UX-series'=>[
            'UX 250h',
        ]
    ],
    'Li Auto'=>[
        'L7',
        'L8',
        'L9'
    ],
    'Lifan'=>[
        '320',
        '330',
        '520',
        '620',
        '720',
        '820',
        'X60',
    ],
    'Lincoln'=>[
        'Aviator',
        'LS',
        'MKZ',
        'Navigator',
        'Town Car'
        ],

    'Lotus'=>[
        'Eletre'
    ],
    'LuAz'=>[
        '969'
    ],
    'Lynk & Co'=>[
        '01',
        '03',
        '05',
        '09',
    ],
    'Mack'=>[
        'Granite'
    ],
    'MAN'=>[
        'F 200',
        'L 2000',
        'TGA 18.400',
        'TGA 18.410',
        'TGA 18.430',
        'TGA 18.440',
        'TGA 18.480',
        'TGA 26.320',
        'TGA 26.440',
        'TGA 33.480',
        'TGA 33350',
        'TGA 480',
        'TGA 33.360',
        'TGA 18.440',
        'TGA 18.480'
    ],
    'Maple'=>[
        'X3 Pro'
    ],
    'Maserati'=>[
        'Ghibli',
        'Gran Turismo',
        'Gran Turismo S',
        'Grecale',
        'Levante',
        'Quattroporte',
    ],
    'MAZ'=>[
        '3577',
        '5334',
        '5337',
        '54322',
        '54323',
        '551605',
        '551630',
        '5549',
        '6303',
        '642208',
        '64229',
        '643008',
        '650108',
    ],
    'Mazda'=>[
        '3',
        '4',
        '6',
        '626',
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-60',
        'CX-7',
        'CX-9',
        'CX-90',
        'MX-30',
        'Premacy',
        'Titan',
        'Tribute',
        'XEDOS',
    ],
    'Mercedes'=>[
        '100',
        '170 V',
        '190',
        'A-Class'=>[
            'A 140',
            'A 150',
            'A 160',
            'A 170',
            'A 180',
            'A 190',
            'A 200',
            'A 220',
            'A 250 e',
            'A 35 AMG 4MATIC',
        ],
        'AMG GT'=>[
            'AMG GT 53',
            'AMG GT 63 S'
        ],
        'B-Class'=>[
            'B 170',
            'B 180',
            'B 200',
        ],
        'C-Class'=>[
            'C 160',
            'C 180',
            'C 200',
            'C 220',
            'C 230',
            'C 240',
            'C 250',
            'C 270',
            'C 280',
            'C 300',
            'C 300 e',
            'C 32 AMG',
            'C 320',
            'C 350',
            'C 350 e',
            'C 43 AMG',
            'C 63 AMG',
        ],
        'CL-Class'=>[
            'CL 500',
            'CL 550'
        ],
        'CLA-Class'=>[
            'CLA 180',
            'CLA 200',
            'CLA 220',
            'CLA 250',
            'CLA 250 e',
            'CLA 35 AMG',
            'CLA 45 S AMG'
        ],
        'CLE-Class'=>[
            'CLE 300 4MATIC'
        ],
        'CLK-Class'=>[
            'CLK 200',
            'CLK 230',
            'CLK 320',
        ],
        'CLS-Class'=>[
            'CLS 250 CDI',
            'CLS 300',
            'CLS 320',
            'CLS 350',
            'CLS 450 Coupe',
            'CLS 500',
            'CLS 550',
            'CLS 63 AMG',
            'CLS 63 AMG',
        ],
        'Citan',
        'Commercial'=>[
            '0303',
            '0403',
            '1117',
            '1217',
            '208 D',
            '308 D',
            '408 D',
            '409 D',
            '410 D',
            '412 D',
            '508',
            '512 D',
            '612 D',
            '709 D',
            '809 D',
            '811 D',
            '813',
            '813',
            '814 D',
            'Actros 1840',
            'Actros 1841',
            'Actros 1842',
            'Actros 1843',
            'Actros 1844',
            'Actros 1846',
            'Actros 1848',
            'Actros 2540',
            'Actros 2544',
            'Actros 2643 L',
            'Actros 3235',
            'Atego 1017',
            'Atego 1217',
            'Atego 1218',
            'Atego 1222',
            'Atego 1223',
            'Atego 1224',
            'Atego 1228',
            'Atego 1317',
            'Atego 1318',
            'Atego 1323',
            'Atego 1324',
            'Atego 1518',
            'Atego 1523',
            'Atego 1524',
            'Atego 1528',
            'Atego 1529',
            'Atego 1622',
            'Atego 1824',
            'Atego 1828',
            'Atego 2528',
            'Atego 809',
            'Atego 811',
            'Atego 812',
            'Atego 813',
            'Atego 814',
            'Atego 815',
            'Atego 816',
            'Atego 817',
            'Atego 818',
            'Atego 822',
            'Atego 917',
            'Atego 918',
            'Atego 1824',
            'Atego 1829',
            'Atego 1833',
            'Atego 1840',
            'Atego 1843',
            'Atego 2529',
            'Atego 2533',
            'Atego 2536',
            'Atego 3028',
            'Atego 3340',
            'Atego 4140',
            'Travego',
            'Vario',
        ],
        'E-Class'=>[
            '200',
            '230 E',
            '240 D',
            'E 180',
            'E 200',
            'E 220',
            'E 230',
            'E 240',
            'E 250',
            'E 260',
            'E 270',
            'E 280',
            'E 290',
            'E 300',
            'E 300 de',
            'E 300 e',
            'E 300 e',
            'E 320',
            'E 350',
            'E 350 e',
            'E 400',
            'E 420',
            'E 43 4MATIC',
            'E 430',
            'E 450 4MATIC',
            'E 500',
            'E 53 4MATIC+',
            'E 53 AMG',
            'E 550',
        ],
        'EQA'=>[
            'EQA 250',
            'EQA 260',
        ],
        'EQC'=>[
            'EQC 400 4MATIC'
        ],
        'EQE'=>[
            'AMG EQE 53 4MATIC',
            'EQE 300',
            'EQE 350',
            'EQE 350 4MATIC',
            'EQE 350 4MATIC SUV',
        ],
        'EQS'=>[
            'AMG EQS 53 4MATIC+',
            'EQS 350',
            'EQS 450 4MATIC SUV',
            'EQS 450+',
            'EQS 500 4MATIC',
            'EQS 580 4MATIC',
            'EQS 580 4MATIC SUV',
        ],
        'EQV'=>[
            'EQV 300'
        ],
        'G-Class'=>[
            'G 300',
            'G 320',
            'G 350',
            'G 400',
            'G 500',
            'G 55 AMG',
            'G 63 AMG',
            'G 65 AMG',
        ],
        'GL-Class'=>[
            'GL 320',
            'GL 350',
            'GL 400',
            'GL 450',
            'GL 500',
            'GL 550',
            'GL 63 AMG',
        ],
        'GLA-Class'=>[
            'GLA 200',
            'GLA 250'
        ],
        'GLB-Class'=>[
            'GBL 200',
            'GBL 220',
            'GBL 250',
        ],
        'GLC-Class'=>[
            'GLC 200 4MATIC',
            'GLC 200 4MATIC+ Coupe',
            'GLC 200  Coupe',
            'GLC 220',
            'GLC 220 d 4MATIC Coupe',
            'GLC 250',
            'GLC 250 Coupe',
            'GLC 300',
            'GLC 300 Coupe',
            'GLC 300 e 4MATIC',
            'GLC 300 e 4MATIC+Coupe',
            'GLC 63S AMG'
        ],
        'GLE-Class'=>[
            'GLE 250',
            'GLE 300',
            'GLE 350',
            'GLE 350 Coupe',
            'GLE 400',
            'GLE 400 Coupe',
            'GLE 43 AMG',
            'GLE 43 AMG Coupe',
            'GLE 450',
            'GLE 450 4MATIC+',
            'GLE 450 4MATIC+ Coupe',
            'GLE 450 AMG Coupe',
            'GLE 53 AMG',
            'GLE 53 AMG Coupe',
            'GLE 63 AMG S',
            'GLE 63 AMG S 4MATIC+Coupe',
            'GLE 63 AMG S 4MATIC+Coupe'
        ],
        'GLK-Class'=>[
            'GLK 220',
            'GLK 350',
        ],
        'GLS-Class'=>[
            'GLS 350',
            'GLS 400',
            'GLS 450',
            'GLS 500',
            'GLS 580',
            'GLS 63 AMG'
        ],
        'ML-Class'=>[
            'ML 250',
            'ML 270',
            'ML 300',
            'ML 320',
            'ML 350',
            'ML 400',
            'ML 430',
            'ML 500',
            'ML 63 AMG',
        ],
        'R-Class'=>[
            'R 320'
        ],
        'S-Class'=>[
            '280 SEL',
            '500 SE',
            'S 250',
            'S 280',
            'S 300',
            'S 300 h',
            'S 320',
            'S 350',
            'S 350 d',
            'S 350 d 4MATIC',
            'S 400',
            'S 400 d',
            'S 400 d 4MATIC',
            'S 420',
            'S 430',
            'S 450',
            'S 450 4MATIC',
            'S 500',
            'S 500 4MATIC',
            'S 550',
            'S 550 e',
            'S 560 4MATIC',
            'S 580 4MATIC',
            'S 600',
            'S 63',
            'S 63 AMG Coupe',
            'S 65 AMG',
        ],
        'SLK-Class'=>[
            'SLK 230'
        ],
        'Sprinter'=>[
            'Sprinter 208',
            'Sprinter 209',
            'Sprinter 210',
            'Sprinter 211',
            'Sprinter 212',
            'Sprinter 213',
            'Sprinter 215',
            'Sprinter 219',
            'Sprinter 308',
            'Sprinter 310',
            'Sprinter 311',
            'Sprinter 312',
            'Sprinter 313',
            'Sprinter 315',
            'Sprinter 316',
            'Sprinter 318',
            'Sprinter 319',
            'Sprinter 412',
            'Sprinter 413',
            'Sprinter 416',
            'Sprinter 511',
            'Sprinter 515',
            'Sprinter 516',
            'Sprinter 518',
        ],
        'V-Class'=>[
            'V 220',
            'V 230',
            'V 250',
            'V 300',
            'Viano',
        ],
        'Vaneo',
        'Vito'=>[
            'Vito',
            'Vito 108',
            'Vito 109',
            'Vito 110',
            'Vito 111',
            'Vito 112',
            'Vito 113',
            'Vito 114',
            'Vito 115',
            'Vito 116',
            'Vito 119',
            'Vito 120',
            'Vito 126',
            'Vito 126'
        ]
    ],
    'Mercedes-Maybach'=>[
        'EQS 680 4MATIC SUV',
        'GLS 600 4MATIC',
        'S 400',
        'S 450',
        'S 500',
        'S 560',
        'S 580 4MATIC ',
    ],
    'MG'=>[
        '3',
        '350',
        '4 EV',
        '5',
        '550',
        'GT',
        'One',
        'RX8',
        'ZS',
    ],
    'Mini'=>[
        'Clubman',
        'Cooper',
        'Countryman',
    ],
    'Minsk'=>[
        'D4 125',
        'SCR 250',
        'X250'
    ],
    'Mitsubishi'=>[
        'ASX',
        'Airtrek',
        'Attrage',
        'Canter',
        'Carisma',
        'Chariot',
        'Eclipse Cross',
        'Galant',
        'Grandis',
        'L200',
        'L300',
        'Lancer',
        'Lancer Evolution',
        'Mirage',
        'Montero',
        'Nativa',
        'Outlander',
        'Outlander Sport',
        'Pajero',
        'Pajero Pinin',
        'Pajero Sport',
        'Pajero io',
        'Rosa',
        'Space Star',
        'Xpander'
    ],
    'Mondial'=>[
        '100 Loyal',
        '50 Revival',
        '50 ZNU',
        'X-Treme MAXX-200'
    ],
    'Moskvich'=>[
        '2140',
        '2141',
        '2715',
        '401',
        '407',
        '408',
        '412'
    ],
    'Moto Guzzi'=>[
        'Eldorado'
    ],
    'Muravey'=>[
        'Muravey-2 01',
        'Muravey-2 02',
        'Muravey-2 03',
        'TG200',
        'TGA200',
        'TGA200-01P'
    ],
    'MV Agusta'=>[
        'F3 800'
    ],
    'Nissan'=>[
        'Almera',
        'Altima',
        'Armada',
        'Bluebird',
        'Juke',
        'Kicks',
        'Leaf',
        'March',
        'Maxima',
        'Micra',
        'Murano',
        'Navara',
        'Note',
        'Pathfinder',
        'Patrol',
        'Presage',
        'Primastar',
        'Primera',
        'Qashqai',
        'Quest',
        'Sentra',
        'Skyline',
        'Sunny',
        'Teana',
        'Terrano',
        'Tiida',
        'Versa',
        'Wingroad',
        'X-Trail',
        'Xterra'
    ],
    'Opel'=>[
        'Antara',
        'Astra',
        'Combo',
        'Corsa',
        'Crossland X',
        'Frontera',
        'Grandland X',
        'Insignia',
        'Kadett',
        'Meriva',
        'Mokka',
        'Monterey',
        'Movana',
        'Omega',
        'Signum',
        'Sintra',
        'Tigra',
        'Vectra',
        'Vita',
        'Vivaro',
        'Zafira'
    ],
    'Parvaz'=>[
        'GS 200'
    ],
    'PAZ'=>[
        '32054'
    ],
    'Peugeot'=>[
        '2008'=>[
            '2008',
            'e-2008',
        ],
        '206',
        '207',
        '208',
        '3008',
        '301',
        '307',
        '308'=>[
            '308',
            '308 SW'
        ],
        '405',
        '406',
        '407',
        '5008',
        '605',
        '607',
        '807',
        'Bipper',
        'Khazar 406',
        'Partner',
        'RCZ',
        'Rifter',
    ],
    'Polad'=>[
        'S 50'
    ],
    'Polaris'=>[
        'RZR XP 1000'
    ],
    'Polestar'=>[
        '2'
    ],
    'Pontiac'=>[
        'Solstice'
    ],
    'Porsche'=>[
        '911'=>[
            '911 Carrera',
            '911 Carrera 4S',
        ],
        'Cayenne'=>[
            'Cayenne',
            'Cayenne Coupe',
            'Cayenne E-Hybrid',
            'Cayenne E-Hybrid Coupe',
            'Cayenne GTS',
            'Cayenne GTS Coupe',
            'Cayenne S',
            'Cayenne S Coupe',
            'Cayenne Turbo',
            'Cayenne Turbo S'
        ],
        'Macan'=>[
            'Macan',
            'Macan GTS',
            'Macan S',
            'Macan T',
            'Macan Turbo',
        ],
        'Panamera'=>[
            'Panamera',
            'Panamera 4',
            'Panamera 4 E-Hybrid',
            'Panamera 4 E-Executive',
            'Panamera 4S',
            'Panamera 4S E-Hybrid',
            'Panamera 4S E-Executive',
            'Panamera GTS',
            'Panamera S',
            'Panamera Turbo',
            'Panamera Turbo Executive',
            'Panamera Turbo S',
        ],
        'Taycan'=>[
            'Taycan',
            'Taycan 4S',
            'Taycan GTS',
            'Taycan Turbo S',
        ]
    ],
    'Radar'=>[
        'RD6'
    ],
    'RAF'=>[
        '2203',
        '22031',
    ],
    'Ravon'=>[
        'Nexia R3',
        'R2',
        'R4',
    ],
    'Renault'=>[
        '12 Toros',
        'Arkana',
        'Clio',
        'Dokker',
        'Duster',
        'Fluence',
        'Grand Scenic',
        'Kangoo',
        'Kaptur',
        'Laguna',
        'Magnum',
        'Megane',
        'Megane Scenic',
        'Modus',
        'Premium 250',
        'Premium 420',
        'Premium 460',
        'Sandero',
        'Scenic',
        'Symbol',
        'Tondar',
    ],
    'RKS'=>[
        'Pollo 50'
    ],
    'Roewe'=>[
        '350'
    ],
    'Roll-Royce'=>[
        'Cullinan',
        'Phantom',
        'Wraith',
    ],
    'Rover'=>[
        '75'
    ],
    'Royal Enfield'=>[
        'Classic 350',
        'Hunter 350',
        'Meteor 350',
    ],
    'Saipa'=>[
        '132',
        '141',
        'Saina',
        'Tiba',
    ],
    'Scania'=>[
        '124 L',
        'R420',
        'R480',
        'R500',
    ],
    'SEAT'=>[
        'Exeo',
        'Ibiza',
        'Leon',
        'Toledo',
    ],
    'Seres'=>[
        '7'
    ],
    'Setra'=>[
        '215 HD'
    ],
    'Shacman'=>[
        'F2000',
        'F3000',
        'SX331DV326',
    ],
    'Shaolin'=>[
        'SLG 6602'
    ],
    'Skoda'=>[
        'Fabia',
        'Felicia',
        'Kamiq',
        'Karoq',
        'Kadiaq',
        'Octavia',
        'Praktik',
        'Rapid',
        'Scala',
        'Superb',
        'Yeti',
    ],
    'Skywell'=>[
        'ET5',
        'HT-i',
    ],
    'Smart'=>[
        'Forfour',
        'Fortwo',
    ],
    'Soueast'=>[
        'A5',
        'DX5',
    ],
    'Sport'=>[
        'Minik'
    ],
    'Ssang Yong'=>[
        'Actyon',
        'Actyon Sports',
        'Chairman',
        'Korando',
        'Kyron',
        'Rexton',
        'Tivoli',
    ],
    'Subaru'=>[
        'B9 Tribeca',
        'BRZ',
        'Forester',
        'Impreza',
        'Impreza WRX STi',
        'Legacy',
        'Outback',
        'Tribeca',
        'XV',
    ],
    'Suzuki'=>[
        'Aerio',
        'Burgman',
        'Fronx',
        'Grand Vitara',
        'Ignis',
        'Jimny',
        'Kizashi',
        'SX4',
        'Splash',
        'Suzuki Moto'=>[
            'AN 125',
            'Boulevard',
            'GSR 600',
            'GSR 750',
            'GSX 1300 R Hayabusa',
            'GSX-S 750',
            'GSX-S1000',
            'Inazuma 250',
            'Intruder M-800',
            'Kingquad 750',
        ],
        'Swift',
        'Vitara',
    ],
    'SYM'=>[
        'X-PRO'
    ],
    'Tatra'=>[
        '815'
    ],
    'Temsa'=>[
        'Prestij Super Deluxe'
    ],
    'Tesla'=>[
        'Model 3',
        'Model S',
        'Model X',
        'Model Y',
    ],
    'Tofas'=>[
        'Dogan',
        'Kartal',
        'Sahin',
    ],
    'Toyota'=>[
        '4Runner',
        'Alphard',
        'Auris',
        'Avalon',
        'Avensis',
        'C-HR',
        'Camry',
        'Corolla',
        'Corolla Cross',
        'Corolla Verso',
        'Crown',
        'FJ Cruiser',
        'Fortuner',
        'Harrier',
        'HiAce',
        'Highlander',
        'Hilux',
        'IQ',
        'Ipsum',
        'Land Cruiser',
        'Matrix',
        'Prado',
        'Previa',
        'Prius',
        'Prius C',
        'Prius Prime',
        'Prius V',
        'Proace',
        'Rav4',
        'Rush',
        'Sequoia',
        'Sienna',
        'Sienta',
        'Solara',
        'Surf',
        'Tacoma',
        'Tundra',
        'Urban Cruiser',
        'Venza',
        'Verso',
        'Vitz',
        'Yaris',
        'Yaris Cross',
        'bZ3',
        'bZ4X'
    ],
    'Tufan'=>[
        'CR 200',
        'CUB50',
        'CUB50 S',
        'City 125',
        'City 50',
        'Istiqlal',
        'M50',
    ],
    'UAZ'=>[
        '2206',
        '31512',
        '31514',
        '31519',
        '3303',
        '33036',
        '33094',
        '39625',
        '452',
        '462',
        '469',
        'Hunter',
        'Patriot',
        'Pickup',
        'Profi',
    ],
    'Ural'=>[
        '4320',
        'DNEPR MT',
    ],
    'Vespa'=>[
        'GTS 300',
        'Primavera 125',
        'SXL 150',
        'VXL 150',
    ],
    'VGV'=>[
        'U70 Pro',
        'U75 Plus',
    ],
    'Volkswagen'=>[
        'Amarok',
        'Arteon',
        'Atlas',
        'Beetle',
        'Bora',
        'Caddy',
        'Caravella',
        'Corrado',
        'Crafter',
        'Golf',
        'Golf GTI',
        'Golf Plus',
        'ID.3',
        'ID.4',
        'ID.6',
        'Jetta',
        'LT',
        'Multivan',
        'Passat',
        'Passat CC',
        'Phaeton',
        'Pointer',
        'Polo',
        'Sharan',
        'Taos',
        'Tayron',
        'Tiguan',
        'Touareg',
        'Touran',
        'Transporter',
        'Vento',
        'e-Bora',
    ],
    'Volvo'=>[
        '440',
        '460',
        '740',
        '850',
        '940',
        '960',
        'FH 12',
        'FH 13',
        'FH 460',
        'FH 500',
        'FL 220',
        'S60',
        'S70',
        'S80',
        'S90',
        'V40',
        'XC60',
        'XC90',
    ],
    'Voyah'=>[
        'Dream',
        'Free',
        'Passion',
    ],
    'Wuling'=>[
        'Air Ev',
        'Hongguang Mini Ev',
    ],
    'XCMG'=>[
        'QY16G.5'
    ],
    'XPeng'=>[
        'G9',
        'P7',
    ],
    'Yamaha'=>[
        'Crux',
        'Cygnus Alpha',
        'FZ-S F Deluxe',
        'FZ-X',
        'FZ25',
        'Grizzly 700',
        'MT-15',
        'R15',
        'R15M',
        'R15S',
        'RAY-ZR',
        'RAY Z 115',
        'RAYZR Street Rally 125',
        'SR 250',
        'V max',
        'Vino',
        'XV1700 Road Star Warrior',
        'YBR 125',
        'YP400 Majesty',
        'YZ250F',
        'YZF-R25',
    ],
    'Yutong'=>[
        '6831'
    ],
    'ZAZ'=>[
        '965',
        '968M',
        'Lanos',
        'Slavuto',
        'Tavriya',
        'Vida',
    ],
    'ZEEKR'=>[
        '001',
        '009',
        'X',
    ],
    'ZIL'=>[
        '130',
        '131',
        '133',
        '431410',
        '431412',
        '4334',
        '5301',
        'MMZ 45023',
    ],
    'Zongshen'=>[
        'Infinity',
        'Spex',
        'ZII ZS200-76',
    ],
    'Zontes'=>[
        'Panther ZT150-8A',
        'R310',
        'Tiger ZT150-3A',
        'X310',
        'ZT155-G1',
    ],
    'ZX Auto'=>[
        'Terralord'
    ]
];
return $this->success($cars);
        foreach ($cars as $markName => $models) {
            $mark = VehicleBrand::create(['name' => $markName]);

            foreach ($models as $modelNamet => $modelName) {
                if (is_array($modelName)) {
                    $lastEvhicleModelId = VehicleModel::create([
                        'vehicle_brand_id' => $mark->id,
                        'name' => $modelNamet,
                        'parent_id' => 0
                    ])->id;
                    foreach ($modelName as $subModelName) {
                        VehicleModel::create([
                            'vehicle_brand_id' => $mark->id,
                            'name' => $subModelName,
                            // 'parent_id' => $mark->vehicleModels->firstWhere('name', $modelName)->id
                            'parent_id' => $lastEvhicleModelId
                        ]);
                    }
                } else {
                    VehicleModel::create([
                        'vehicle_brand_id' => $mark->id,
                        'name' => $modelName,
                        'parent_id' => 0
                    ]);
                }
            }
        }
        return 1;
    }
}
